export {
  getCurrentUser,
  updateProfile,
  uploadAvatar,
  toStoredAuthUser,
  type GetCurrentUserResult,
  type UpdateProfileInput,
  type UpdateProfileResult,
  type UploadAvatarResult,
  type UserProfile,
} from "./account";

export {
  getExpertById,
  type Expert,
  type ExpertProgram,
  type GetExpertByIdResponse,
  type GetExpertByIdResult,
  type ProgramExpert,
} from "./experts";

export {
  createProgram,
  deleteProgram,
  getProgramById,
  getProgramCurriculum,
  getProgramReviews,
  getPrograms,
  getProgramsWithModules,
  updateProgram,
  type CreateProgramInput,
  type CreateProgramResponse,
  type CreateProgramResult,
  type CurriculumModule,
  type DeleteProgramResponse,
  type DeleteProgramResult,
  type GetProgramByIdResponse,
  type GetProgramByIdResult,
  type GetProgramCurriculumResponse,
  type GetProgramCurriculumResult,
  type GetProgramReviewsResponse,
  type GetProgramReviewsResult,
  type GetProgramsResponse,
  type GetProgramsResult,
  type GetProgramsWithModulesResponse,
  type GetProgramsWithModulesResult,
  type Module,
  type ModuleCourse,
  type ModuleType,
  type Paginated,
  type Program,
  type ProgramCurriculum,
  type ProgramIdParam,
  type ProgramLevel,
  type ProgramListQuery,
  type ProgramReview,
  type ProgramReviewsQuery,
  type ProgramWithModules,
  type UpdateProgramInput,
  type UpdateProgramResponse,
  type UpdateProgramResult,
} from "./programs";

export {
  getModuleById,
  type GetModuleByIdResponse,
  type GetModuleByIdResult,
} from "./modules";

export {
  getCourseById,
  type Course,
  type CurriculumCourse,
  type GetCourseByIdResponse,
  type GetCourseByIdResult,
} from "./courses";

export {
  getActivityById,
  type Activity,
  type ActivityLearningProgress,
  type ActivityMaterial,
  type ActivityType,
  type CurriculumActivity,
  type CurriculumMaterialSummary,
  type GetActivityByIdOptions,
  type GetActivityByIdResponse,
  type GetActivityByIdResult,
} from "./activities";

export {
  getMaterialByActivityId,
  type GetMaterialByActivityResponse,
  type GetMaterialByActivityResult,
  type Material,
} from "./materials";

export {
  cancelPayment,
  checkoutPayment,
  getPaymentById,
  parentCheckout,
  requestParentPayment,
  type CheckoutPaymentInput,
  type CheckoutPaymentResponse,
  type CheckoutPaymentResult,
  type CheckoutSession,
  type GetPaymentByIdResponse,
  type GetPaymentByIdResult,
  type ParentCheckoutInput,
  type ParentCheckoutResponse,
  type ParentCheckoutResult,
  type ParentCheckoutSession,
  type Payment,
  type PaymentGateway,
  type PaymentStatus,
  type RequestParentPaymentInput,
  type RequestParentPaymentResponse,
  type RequestParentPaymentResult,
} from "./payments";

export {
  completeActivity,
  getEnrollmentCurriculum,
  getMyProgramEnrollments,
  getProgramEnrollmentsByStudentId,
  saveActivityCheckpoint,
  type ActivityCheckpointData,
  type ActivityNavStatus,
  type CompleteActivityData,
  type CompleteActivityInput,
  type CompleteActivityResponse,
  type CompleteActivityResult,
  type EnrollmentCurriculum,
  type EnrollmentCurriculumActivity,
  type EnrollmentCurriculumCourse,
  type EnrollmentCurriculumMilestone,
  type EnrollmentCurriculumModule,
  type GetEnrollmentCurriculumResponse,
  type GetEnrollmentCurriculumResult,
  type GetMyProgramEnrollmentsResponse,
  type GetMyProgramEnrollmentsResult,
  type GetStudentProgramEnrollmentsResponse,
  type GetStudentProgramEnrollmentsResult,
  type MyProgramEnrollmentsQuery,
  type ProgramEnrollment,
  type ProgramEnrollmentStatus,
  type ResumeState,
  type ResumeStateKind,
  type SaveActivityCheckpointInput,
  type SaveActivityCheckpointResponse,
  type SaveActivityCheckpointResult,
  type StudentProgramEnrollmentsQuery,
} from "./program-enrollments";

export {
  approveParentLink,
  completeParentProfile,
  getParentLinks,
  parentMagicLogin,
  requestParentLink,
  type ApproveParentLinkInput,
  type ApproveParentLinkResponse,
  type ApproveParentLinkResult,
  type CompleteParentProfileInput,
  type CompleteParentProfileResponse,
  type CompleteParentProfileResult,
  type GetParentLinksResponse,
  type GetParentLinksResult,
  type ParentLinkedStudent,
  type ParentMagicLoginInput,
  type ParentMagicLoginResponse,
  type ParentMagicLoginResult,
  type RequestParentLinkInput,
  type RequestParentLinkResponse,
  type RequestParentLinkResult,
} from "./parent";

export {
  register,
  verifyOtp,
  login,
  refreshToken,
  sendResetLink,
  forgotPassword,
  type RegisterInput,
  type VerifyOtpInput,
  type LoginInput,
  type RefreshTokenInput,
  type SendResetLinkInput,
  type ForgotPasswordInput,
  type RegisteredUser,
  type AuthTokens,
  type RegisterResponse,
  type VerifyOtpResponse,
  type LoginResponse,
  type RefreshTokenResponse,
  type SendResetLinkResponse,
  type ForgotPasswordResponse,
  type RegisterResult,
  type VerifyOtpResult,
  type LoginResult,
  type RefreshTokenResult,
  type SendResetLinkResult,
  type ForgotPasswordResult,
} from "./auth";

export { createApiPost } from "./create-endpoint";
export { ApiRequestError, ApiResponseError } from "./errors";
export {
  apiFetch,
  apiFetchParsed,
  assertApiSuccess,
  getApiBaseUrl,
  type ApiFetchOptions,
} from "./client";
export {
  apiErrorSchema,
  apiValueMessageOnlySchema,
  createApiResponseSchema,
  createApiValueSchema,
  type ApiEnvelope,
  type ApiError,
} from "./schemas";
