services:
  obox-frontend:
    image: ${DOCKERHUB_USERNAME}/oboxsteam-fe:latest
    container_name: obox-frontend
    pull_policy: always
    restart: always
    environment:
      NODE_ENV: production
    networks:
      - shared_network

networks:
  shared_network:
    external: true
